class Kxdesk < Formula
  desc "Personal desktop daemon for SketchyBar, yabai and friends"
  homepage "https://github.com/kvndrsslr/kxdesk"
  url "https://github.com/kvndrsslr/kxdesk.git",
      tag:      "v0.1.23",
      revision: "f01b612bd8620c8aaad76e650ad8c9e8e3fbed7b"
  head "https://github.com/kvndrsslr/kxdesk.git", branch: "main"

  depends_on "zig" => :build
  depends_on :macos
  depends_on "terminal-notifier"

  def install
    system "zig", "build", "--prefix", prefix

    # Both scripts are generated by the binary (`kxdesk completions <shell>`)
    # rather than shipped beside it, so what lands in the completion directories
    # cannot describe a command this build does not have. Default shells are
    # bash, zsh and fish; fish is not offered.
    #
    # This runs the binary at install time, so the pinned `url` above has to be a
    # tag that already has `completions` - v0.1.23 does not, and a non-HEAD
    # install from it would fail here. Bump the pin with the next release.
    generate_completions_from_executable(bin/"kxdesk", "completions", shells: [:bash, :zsh])
  end

  service do
    run [opt_bin/"kxdesk", "daemon"]
    keep_alive true
    process_type :interactive
  end

  test do
    # Every other command is answered by the daemon, and `brew test` does not
    # start one; the version, the help and the completions are the questions the
    # binary answers itself.
    assert_match(/\d+\.\d+\.\d+/, shell_output("#{bin}/kxdesk version"))
    assert_match("_kxdesk", shell_output("#{bin}/kxdesk completions zsh"))
    assert_match("_kxdesk", shell_output("#{bin}/kxdesk completions bash"))
  end
end
